name: dish_dash
description: "A Flutter app to search, find, and dash to great food spots!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # HTTP Requests
  dio: ^5.4.0
  jwt_decode: ^0.3.1

  # Form Validation
  formz: ^0.6.0

  # Map and Location
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

  # UI/UX Improvements
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  anim_search_bar: ^2.0.3

  # Search and Filtering
  search_choices: ^2.2.7

  # Local Storage
  shared_preferences: ^2.2.2
  dartz: ^0.10.1



  # Permission Handling
  permission_handler: ^11.3.1

  # Dev Tools (runtime side)
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

  # Cupertino icons (iOS style)
  cupertino_icons: ^1.0.8
  jwt_decoder: ^2.0.1

  internet_connection_checker: ^1.0.0
  visibility_detector: ^0.4.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation Tools
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo2.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FCFBF9"
  image: "assets/Frame.png"

  android_12:
    color: "#FCFBF9"
    image: "assets/Frame.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/products/
