# Generated by Django 4.2.1 on 2025-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_storeproduct_product_alter_storeproduct_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
