# Generated by Django 4.2.1 on 2025-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
